### ISSUE TITLE
Error `class extends value undefined`

### ISSUE THREAD

**Issue by KutnerUri** [Siilwyn/prettier-plugin-css-order#37]
Getting this error when trying to run prettier with the plugin:

prettier version: `3.1.1`
plugin version: `2.0.1`
node version: `v20.10.0`

```
npx prettier --plugin prettier-plugin-css-order ./wup.module.scss

➜  CommonRankSlider git:(DEV-4348-filter-fix) ✗ npx prettier --plugin prettier-plugin-css-order ./wup.module.scss
[error] Class extends value undefined is not a constructor or null
/Users/gankster/Documents/projects/gankster-frontend/client/node_modules/prettier-plugin-css-order/node_modules/postcss-scss/lib/nested-declaration.js:3
class NestedDeclaration extends Container {
                                ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/gankster/Documents/projects/gankster-frontend/client/node_modules/prettier-plugin-css-order/node_modules/postcss-scss/lib/nested-declaration.js:3:33)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/gankster/Documents/projects/gankster-frontend/client/node_modules/prettier-plugin-css-order/node_modules/postcss-scss/lib/scss-parser.js:4:25)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

Node.js v20.10.0
```

.prettierrc:
```json
{
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all",
  "arrowParens": "avoid",
  "endOfLine": "lf"
}
```

**Comment by Siilwyn** [comment]
Does this always happen regardless of the CSS you're sorting? If not please provide a minimal reproduction with the CSS that causes it.

**Comment by Siilwyn** [comment]
Needs reproduction, closing for now.
