### ISSUE TITLE
'Unkown word' errors with some SCSS implementations

### ISSUE THREAD

**Issue by johnvanhulsen** [Siilwyn/prettier-plugin-css-order#4]
Hi,

Use your plugin with pleasure but we notice with certain scss code that it doesn't work flawlessly.

For example:
```scss
margin-left: -#{$grid-default-gutter / 2};
```

```scss
left: -#{ceil($height / 100 * $skewDeg)};
```

and 
```scss
@mixin btn-color($property: 'background-color', $color: $color-base-button) {
  #{$property}: $color;
}
```

The following errors are given:
```
assets/css/01-tools/mixins/_button-color.scss
[error] assets/css/01-tools/mixins/_button-color.scss: CssSyntaxError: <css input>:8:5: Unknown word
[error]     at Input.error (***/node_modules/.pnpm/postcss@8.3.6/node_modules/postcss/lib/input.js:123:16)
[error]     at Parser.unknownWord (***/node_modules/.pnpm/postcss@8.3.6/node_modules/postcss/lib/parser.js:518:22)
[error]     at Parser.other (***/node_modules/.pnpm/postcss@8.3.6/node_modules/postcss/lib/parser.js:149:12)
[error]     at Parser.parse (***/node_modules/.pnpm/postcss@8.3.6/node_modules/postcss/lib/parser.js:59:16)
[error]     at parse (***/node_modules/.pnpm/postcss@8.3.6/node_modules/postcss/lib/parse.js:11:12)
[error]     at new LazyResult (***/node_modules/.pnpm/postcss@8.3.6/node_modules/postcss/lib/lazy-result.js:133:16)
[error]     at Processor.process (***/node_modules/.pnpm/postcss@8.3.6/node_modules/postcss/lib/processor.js:36:12)
[error]     at ***/node_modules/.pnpm/prettier-plugin-css-order@1.0.0_prettier@2.3.0/node_modules/prettier-plugin-css-order/src/sorter.js:7:6
[error]     at runAsWorker (***/node_modules/.pnpm/sync-threads@1.0.1/node_modules/sync-threads/src/index.js:48:18)
[error]     at Object.<anonymous> (***/node_modules/.pnpm/prettier-plugin-css-order@1.0.0_prettier@2.3.0/node_modules/prettier-plugin-css-order/src/sorter.js:5:1)
```

I've try to ignore these parts inline, with options like `/* prettier-ignore */`. But it doesn't care.
Without the plugin it goes well in Prettier.

Can you help me? Thnx!

**Used versions**
`"prettier": "2.3.0",`
`"prettier-plugin-css-order": "^1.0.0",`

**Comment by Siilwyn** [comment]
Thanks for reporting!
:tada: published new SCSS comment support in `1.1.0`
